name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    
      # testing
    - name: executing remote ssh commands using password
      run: |
        cd /home/anthony/projects/discordBot
        git pull
        cd /home/anthony/scripts
    
    - name: restarting discordBot
      run: |
        cd /home/anthony/scripts
        ./restartDiscordbot